### PR TITLE
fix: Mobile support

### LINKED ISSUE #80: Mobile support
Make the different views be supported on mobile according to the designs.

### PR DESCRIPTION
**Pull request by fzavalia**
Closes #80 

Decentraland _ Authorization
Decentraland _ Authorization copy

### CODE REVIEW

File: src/components/Pages/SetupPage/SetupPage.tsx [hunk 1]
```diff
@@ -299,6 +337,68 @@ export const SetupPage = () => {
     )
   }
 
+  if (isMobile) {
```
Comment (fzavalia) [inline src/components/Pages/SetupPage/SetupPage.tsx:340]: I'd like to move these states to different files on a different PR
- Randomize
- Form
- Mobile Randomize
- Mobile Form

Comment (fzavalia) [reply src/components/Pages/SetupPage/SetupPage.tsx:340]: Also there is a bunch of repeated code I'd like to abstract. Not on this PR because the diff would be to ugly.

File: src/components/Pages/SetupPage/SetupPage.tsx [hunk 2]
```diff
@@ -47,6 +47,8 @@ export const SetupPage = () => {
 
   const redirectTo = useAfterLoginRedirection()
 
+  const isMobile = useMemo(() => window.innerWidth <= 768, [])
```
[the remark this answers is not in the document]
Comment (LautaroPetaccio) [reply src/components/Pages/SetupPage/SetupPage.tsx:50]: We do! It's under the `Media` in the UI

File: src/components/Pages/SetupPage/SetupPage.module.css [hunk 3]
```diff
@@ -26,21 +26,21 @@
...
 }
 
-.left :global(.ui.sub.header) > label {
+:global(.ui.sub.header) > label {
   color: white !important;
   opacity: 70%;
 }
 
-.left input {
+input {
```
Comment (LautaroPetaccio) [inline src/components/Pages/SetupPage/SetupPage.module.css:39]: Does this work when using CSS modules?

Comment (fzavalia) [reply src/components/Pages/SetupPage/SetupPage.module.css:39]: It does, I believe that css modules don't scope elements given that technically it would not be possible.

Comment (fzavalia) [reply src/components/Pages/SetupPage/SetupPage.module.css:39]: image

Comment (fzavalia) [reply src/components/Pages/SetupPage/SetupPage.module.css:39]: I should still scope it with something to prevent it from overriding other inputs elsewhere

**Review by LautaroPetaccio — APPROVED** [review]
