### PR TITLE
fix: Button message depending on redirect

### LINKED ISSUE #81: Continue button message depending on the redirect param
Continue button, the one that finishes the profile creation flow. Should show a different message depending on what the redirectTo query param is. For example, if the redirect is to the marketplace, the button should say "CONTINUE TO MARKETPLACE"

### PR DESCRIPTION
**Pull request by fzavalia**
Closes #81

### CODE REVIEW

File: src/components/Pages/SetupPage/SetupPage.tsx [hunk 1]
```diff
@@ -321,7 +341,7 @@ export const SetupPage = () => {
                 </div>
                 <div className={styles.continue}>
                   <Button primary fluid onClick={handleContinue}>
-                    continue
+                    Continue
```
Comment (fzavalia) [inline src/components/Pages/SetupPage/SetupPage.tsx:344]: These are the ones fro the randomization page. They don't matter. Just capitalized it for irrelevant reasons as buttons show text in all caps.

**Review by LautaroPetaccio — APPROVED** [review]
