### PR TITLE
fix: Add tracking events

### LINKED ISSUE #79: Add event tracking
- Avatar Edit Success
- Terms of service success
- Click button (for randomize)

### PR DESCRIPTION
**Pull request by fzavalia**
Closes #79

### CODE REVIEW

File: src/components/Pages/SetupPage/SetupPage.tsx [hunk 1]
```diff
@@ -79,17 +81,52 @@ export const SetupPage = () => {
...
+      action: ClickEvents.RANDOMIZE
+    })
+
+    setProfile(getRandomDefaultProfile())
+  }, [])
+
+  // Confirms the current default profile and goes to the form view.
+  const handleContinue = useCallback(() => {
+    getAnalytics().track(TrackingEvents.AVATAR_EDIT_SUCCESS, {
+      // eslint-disable-next-line @typescript-eslint/naming-convention
```
Comment (fzavalia) [inline src/components/Pages/SetupPage/SetupPage.tsx:96]: Ignoring this rule as analytic events use a different casing than in our dapp standards

File: src/components/Pages/SetupPage/SetupPage.tsx [hunk 2]
```diff
@@ -125,6 +162,15 @@ export const SetupPage = () => {
           }
         }
 
+        getAnalytics().track(TrackingEvents.TERMS_OF_SERVICE_SUCCESS, {
+          // eslint-disable-next-line @typescript-eslint/naming-convention
+          eth_address: accountRef.current,
+          // eslint-disable-next-line @typescript-eslint/naming-convention
+          is_guest: false,
+          email: email || undefined,
```
Comment (fzavalia) [inline src/components/Pages/SetupPage/SetupPage.tsx:170]: email can be an empty string at this point. Sending it as undefined to prevent issues.

**Review by LautaroPetaccio — APPROVED** [review]
🚢
